# Site settings
title: a-boy  曾经多少的痴心迷恋 只与爱情无关
keywords: 诗歌,数学,音乐原创,Web,javascript,HTML,编程,极限学习,科技创造
email: avvboy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    纯情主义
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://a-boy.github.io" # the base hostname & protocol for your site

twitter_username: codyluo369502
github_username:  a-boy

permalink: /:categories/:title
#permalink: /:categories/:title:output_ext

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE